# Generated by Django 4.0.4 on 2022-05-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=122)),
                ('Last_Name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('Username', models.CharField(max_length=122)),
                ('Password', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
    ]
