# Generated by Django 4.0.4 on 2022-05-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_signin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='First_Name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='Last_Name',
            new_name='LastName',
        ),
    ]
