# Generated by Django 4.0.4 on 2022-05-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_rename_first_name_signin_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='FirstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='LastName',
            new_name='lastname',
        ),
    ]
