# Generated by Django 4.0.4 on 2022-05-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_rename_firstname_signin_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('username', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='SignIn',
        ),
    ]
