# Generated by Django 4.0.4 on 2022-05-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_users_delete_signin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
