# Generated by Django 4.0.4 on 2022-05-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='name',
        ),
    ]
